### PR TITLE
Tutorial fix

### PR DESCRIPTION
**Pull request by dchung0741**

### CODE REVIEW

**Comment by ThomasenQunasys** [comment]
Oh, you added the tutorials too? I was working on fixing those at the same time 😆

**Comment by dchung0741** [comment]
Oh I think I misread your message earlier so was fixing both😅 I think I'll rebase this on your PR and let it fix only the examples. 
BTW, I'm looking at the CDR tutorial and it's throwing a weird error message. It's likely a quri-parts bug somewhere.

**Comment by ThomasenQunasys** [comment]
Thanks! And great work btw. Let me know when it's ready 😄

**Comment by dchung0741** [comment]
Thanks! I moved stuff over [here](https://github.com/QunaSys/quri-sdk-notebooks/pull/8).

**Pull request closed without merging**
