### PR TITLE
Revise

### PR DESCRIPTION
**Pull request by toru4838**
This PR mirrors the changes introduced in quri-sdk-docusaurus (see [PR #14](https://github.com/QunaSys/quri-sdk-docusaurus/pull/14)) to maintain consistency.

### CODE REVIEW

**Review by ThomasenQunasys — COMMENTED** [review]
Thanks @toru4838 ! It seems like one of the workflows didn't run properly to check the execution so I just tried fixing it. I will just rebase this on main and check that the workflow runs properly

**Review by ThomasenQunasys — APPROVED** [review]
Seems to be running fine now, just re-requested a review from myself and approved

**Comment by ThomasenQunasys** [comment]
Ah, branch protection rules prevent this. Hang on, @dchung0741 could you review this PR?

**Review by dchung0741 — APPROVED** [review]
LGTM! Thank you!

**Pull request merged**
